global:
  scrape_interval: 5s # Set the scrap internval to every 5 sec
  evaluation_interval: 5s # Evaluate rules every 5 sec
scrape_configs:
  - job_name: 'accounts'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['accounts:8080']
  - job_name: 'cards'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'cards:8090' ]