# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: cards-deployment
deploymentLabel: cards

replicaCount: 2

image:
  repository: ribeirodanilo/cards
  tag: latest

containerPort: 8090

service:
  type: ClusterIP
  port: 8090
  targetPort: 8090

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: true
keycloak_enabled: false