# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: eureka-server-deployment
deploymentLabel: eureka-server

replicaCount: 1

image:
  repository: ribeirodanilo/eureka-server
  tag: latest

containerPort: 8070

service:
  type: LoadBalancer
  port: 8070
  targetPort: 8070

config_enabled: true
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false