# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deploymentName: config-server-deployment
deploymentLabel: config-server

replicaCount: 1

image:
  repository: ribeirodanilo/config-server
  tag: latest

containerPort: 8071

service:
  type: ClusterIP
  port: 8071
  targetPort: 8071

config_enabled: false
zipkin_enabled: true
profile_enabled: true
eureka_enabled: false
keycloak_enabled: false