server:
  port: 8071
spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ribeirodanilo/microservices-config.git
          clone-on-start: true
          default-label: main
  sleuth:
    sampler:
      # amostra de log enviado para zipkin (default 10%, e 1 = 100%, minimo é 0 e max é 1)
      percentage: 1
  zipkin:
    baseUrl: http://localhost:9411
    sender:
      # valor default type: web sync e rabbit para async
      type: web
    rabbitmq:
      # nome da fila criada no rabbitmq
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
encrypt:
  key: minhasenhaparaencriptacao
